run:
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (0,'(No Move)',0,0,0,18,'(No Description)')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (1,'Pound',100,40,35,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (2,'Karate Chop',100,50,25,1,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (3,'Double Slap',85,15,10,0,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (4,'Comet Punch',85,18,15,0,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (5,'Mega Punch',85,80,20,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (6,'Pay Day',100,40,20,0,'Inflicts regular damage with no additional effect. In-game winner receives money after battle.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (7,'Fire Punch',100,75,15,9,'Has a 10% chance to burn the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (8,'Ice Punch',100,75,15,14,'Has a 10% chance to freeze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (9,'Thunder Punch',100,75,15,12,'Has a 10% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (10,'Scratch',100,40,35,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (11,'Vice Grip',100,55,30,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (12,'Guillotine',30,1,5,0,'Knocks out the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (13,'Razor Wind',100,80,10,0,'Requires a charging turn. Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (14,'Swords Dance',101,0,20,0,'Raises the users Attack by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (15,'Cut',95,50,30,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (16,'Gust',100,40,35,2,'Can hit and has double power against Bounceing, Flying, and Sky Dropped targets.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (17,'Wing Attack',100,60,35,2,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (18,'Whirlwind',101,0,20,0,'Forces target to switch with a random teammate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (19,'Fly',95,90,15,2,'Dodges attacks on first turn, strikes on second.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (20,'Bind',85,15,20,0,'Target cannot switch and takes 1/16 damage per turn for 4-5 turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (21,'Slam',75,80,20,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (22,'Vine Whip',100,45,25,11,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (23,'Stomp',100,65,20,0,'Has a 30% chance to flinch. Double damage if target has used Minimize.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (24,'Double Kick',100,30,30,1,'Hits twice in one turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (25,'Mega Kick',75,120,5,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (26,'Jump Kick',95,100,10,1,'User takes half the damage it would have inflicted as crash damage if the attack does not hit.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (27,'Rolling Kick',85,60,15,1,'Has a 30% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (28,'Sand Attack',100,0,15,4,'Lowers the targets accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (29,'Headbutt',100,70,15,0,'Has a 30% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (30,'Horn Attack',100,65,25,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (31,'Fury Attack',85,15,20,0,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (32,'Horn Drill',30,1,5,0,'Knocks out the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (33,'Tackle',100,50,35,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (34,'Body Slam',100,85,15,0,'Has a 30% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (35,'Wrap',90,15,20,0,'Wraps and squeezes the foe 4 to 5 times.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (36,'Take Down',85,90,20,0,'User receives 1/4 the damage inflicted as recoil.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (37,'Thrash',100,120,10,0,'User cannot select another attack or switch for 2-3 turns, then the user becomes confused.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (38,'Double-Edge',100,120,15,0,'User receives 1/3 the damage inflicted as recoil.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (39,'Tail Whip',100,0,30,0,'Lowers the targets Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (40,'Poison Sting',100,15,35,3,'Has a 30% chance to poison the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (41,'Twineedle',100,25,20,6,'Has a 20% chance to poison the target. Hits twice in one turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (42,'Pin Missile',95,25,20,6,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (43,'Leer',100,0,30,0,'Lowers the targets Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (44,'Bite',100,60,25,16,'Has a 30% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (45,'Growl',100,0,40,0,'Lowers the targets Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (46,'Roar',101,0,20,0,'Forces target to switch with a random teammate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (47,'Sing',55,0,15,0,'Puts the target to sleep.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (48,'Supersonic',55,0,20,0,'Confuses the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (49,'Sonic Boom',90,1,20,0,'Does 20 damage to target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (50,'Disable',100,0,20,0,'Disables the targets last used move for 1-8 turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (51,'Acid',100,40,30,3,'Has a 10% chance to lower the targets Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (52,'Ember',100,40,25,9,'Has a 10% chance to burn the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (53,'Flamethrower',100,90,15,9,'Has a 10% chance to burn the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (54,'Mist',101,0,30,14,'Pokémon on the users team may not have their stats lowered by opponents for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (55,'Water Gun',100,40,25,10,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (56,'Hydro Pump',80,110,5,10,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (57,'Surf',100,90,15,10,'Can hit and has double power against Diving targets.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (58,'Ice Beam',100,90,10,14,'Has a 10% chance to freeze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (59,'Blizzard',70,110,5,14,'Has a 10% chance to freeze the target. Has perfect acc in hail.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (60,'Psybeam',100,65,20,13,'Has a 10% chance to confuse the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (61,'Bubble Beam',100,65,20,10,'Has a 10% chance to lower the targets Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (62,'Aurora Beam',100,65,20,14,'Has a 10% chance to lower the targets Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (63,'Hyper Beam',90,150,5,0,'User cannot attack or switch the turn after using this attack.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (64,'Peck',100,35,35,2,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (65,'Drill Peck',100,80,20,2,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (66,'Submission',80,80,25,1,'User receives 1/4 the damage inflicted as recoil.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (67,'Low Kick',100,1,20,1,'More power against to heavier targets, with a maximum of 120.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (68,'Counter',100,1,20,1,'Inflicts twice the damage the user received from the last physical hit it took.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (69,'Seismic Toss',100,1,20,1,'Inflicts damage equal to the users level.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (70,'Strength',100,80,15,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (71,'Absorb',100,20,25,11,'Heals the user by half the damage inflicted.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (72,'Mega Drain',100,40,15,11,'Heals the user by half the damage inflicted.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (73,'Leech Seed',90,0,10,11,'Steals 1/8 of targets HP every turn. Remains if user switches out.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (74,'Growth',101,0,20,0,'Raises the users Attack and Special Attack by one stage, or two stages in sun.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (75,'Razor Leaf',95,55,25,11,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (76,'Solar Beam',100,120,10,11,'Requires a charging turn. No charge turn in sun, half power in rain or sandstorm.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (77,'Poison Powder',75,0,35,3,'Poisons the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (78,'Stun Spore',75,0,30,11,'Paralyzes the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (79,'Sleep Powder',75,0,15,11,'Puts the target to sleep.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (80,'Petal Dance',100,120,10,11,'User cannot select another attack or switch for 2-3 turns, then the user becomes confused.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (81,'String Shot',95,0,40,6,'Lowers the targets Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (82,'Dragon Rage',100,1,10,15,'Does 40 damage to target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (83,'Fire Spin',85,35,15,9,'Target cannot switch and takes 1/16 damage per turn for 4-5 turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (84,'Thunder Shock',100,40,30,12,'Has a 10% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (85,'Thunderbolt',100,90,15,12,'Has a 10% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (86,'Thunder Wave',100,0,20,12,'Paralyzes the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (87,'Thunder',70,110,10,12,'Has a 30% chance to paralyze the target. Has perfect acc in Rain, 50% in Sun.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (88,'Rock Throw',90,50,15,5,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (89,'Earthquake',100,100,10,4,'Can hit and has double power against Digging targets.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (90,'Fissure',30,1,5,4,'Knocks out the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (91,'Dig',100,80,10,4,'Dodges attacks on first turn, strikes on second.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (92,'Toxic',90,0,10,3,'Badly poisons the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (93,'Confusion',100,50,25,13,'Has a 10% chance to confuse the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (94,'Psychic',100,90,10,13,'Has a 10% chance to lower the targets Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (95,'Hypnosis',60,0,20,13,'Puts the target to sleep.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (96,'Meditate',101,0,40,13,'Raises the users Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (97,'Agility',101,0,30,13,'Raises the users Speed by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (98,'Quick Attack',100,40,30,0,'An extremely fast attack that always strikes first.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (99,'Rage',100,20,20,0,'Each time the user is hit before its next action its Attack rises by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (100,'Teleport',101,0,20,13,'Ends wild battles in-game. No other effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (101,'Night Shade',100,1,15,7,'Inflicts damage equal to the users level.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (102,'Mimic',101,0,10,0,'Copies the targets last used move into Mimics moveslot until user leaves the field.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (103,'Screech',85,0,40,0,'Lowers the targets Defense by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (104,'Double Team',101,0,15,0,'Raises the users evasion by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (105,'Recover',101,0,10,0,'Heals the user by half its max HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (106,'Harden',101,0,30,0,'Raises the users Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (107,'Minimize',101,0,10,0,'Raises the users evasion by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (108,'Smokescreen',100,0,20,0,'Lowers the targets accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (109,'Confuse Ray',100,0,10,7,'Confuses the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (110,'Withdraw',101,0,40,10,'Raises the users Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (111,'Defense Curl',101,0,40,0,'Raises users Defense by one stage. Doubles the power of users Rollout and Ice Ball.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (112,'Barrier',101,0,20,13,'Raises the users Defense by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (113,'Light Screen',101,0,30,13,'Halves damage from opponents special attacks for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (114,'Haze',101,0,30,14,'Resets all Pokémons stat stages to zero.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (115,'Reflect',101,0,20,13,'Halves damage from opponents physical attacks for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (116,'Focus Energy',101,0,30,0,'Raises users critical hit rate two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (117,'Bide',101,1,10,0,'User does nothing for two turns, then deals damage equal to double damage taken.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (118,'Metronome',101,0,10,0,'Randomly selects and uses almost any move in the game.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (119,'Mirror Move',101,0,20,2,'Uses the last move targeted at the user by a Pokémon still on the field.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (120,'Self-Destruct',100,200,5,0,'The user faints.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (121,'Egg Bomb',75,100,10,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (122,'Lick',100,30,30,7,'Has a 30% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (123,'Smog',70,30,20,3,'Has a 40% chance to poison the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (124,'Sludge',100,65,20,3,'Has a 30% chance to poison the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (125,'Bone Club',85,65,20,4,'Has a 10% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (126,'Fire Blast',85,110,5,9,'Has a 10% chance to burn the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (127,'Waterfall',100,80,15,10,'Has a 20% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (128,'Clamp',85,35,15,10,'Target cannot switch and takes 1/16 damage per turn for 4-5 turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (129,'Swift',101,60,20,0,'Has perfect accuracy.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (130,'Skull Bash',100,130,10,0,'Requires a charging turn. Raises users Defense one stage on the charge turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (131,'Spike Cannon',100,20,15,0,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (132,'Constrict',100,10,35,0,'Has a 10% chance to lower the targets Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (133,'Amnesia',101,0,20,13,'Raises the users Special Defense by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (134,'Kinesis',80,0,15,13,'Lowers the targets accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (135,'Soft-Boiled',101,0,10,0,'Heals the user by half its max HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (136,'High Jump Kick',90,130,10,1,'User takes half the damage it would have inflicted as crash damage if the attack does not hit.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (137,'Glare',100,0,30,0,'Paralyzes the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (138,'Dream Eater',100,100,15,13,'Fails unless the target is asleep. Heals the user by half the damage inflicted.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (139,'Poison Gas',90,0,40,3,'Poisons the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (140,'Barrage',85,15,20,0,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (141,'Leech Life',100,20,15,6,'Heals the user by half the damage inflicted.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (142,'Lovely Kiss',75,0,10,0,'Puts the target to sleep.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (143,'Sky Attack',90,140,5,2,'Requires a charging turn. Has a 30% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (144,'Transform',101,0,10,0,'User becomes a copy of the target until it leaves battle.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (145,'Bubble',100,40,30,10,'Has a 10% chance to lower the targets Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (146,'Dizzy Punch',100,70,10,0,'Has a 20% chance to confuse the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (147,'Spore',100,0,15,11,'Puts the target to sleep.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (148,'Flash',100,0,20,0,'Lowers the targets accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (149,'Psywave',100,1,15,13,'Inflicts damage between 50% and 150% of the users level.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (150,'Splash',101,0,40,0,'Its just a splash... Has no effect whatsoever.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (151,'Acid Armor',101,0,20,3,'Raises the users Defense by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (152,'Crabhammer',90,100,10,10,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (153,'Explosion',100,250,5,0,'The user faints.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (154,'Fury Swipes',80,18,15,0,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (155,'Bonemerang',90,50,10,4,'Hits twice in one turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (156,'Rest',101,0,10,13,'User falls asleep for two turns, healing major status and all HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (157,'Rock Slide',90,75,10,5,'Has a 30% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (158,'Hyper Fang',90,80,15,0,'Has a 10% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (159,'Sharpen',101,0,30,0,'Raises the users Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (160,'Conversion',101,0,30,0,'Users type changes to the type of one of its moves at random.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (161,'Tri Attack',100,80,10,0,'Has a 20% chance to burn, freeze, or paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (162,'Super Fang',90,1,10,0,'Inflicts damage equal to half the targets HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (163,'Slash',100,70,20,0,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (164,'Substitute',101,0,10,0,'Creates a Substitute using 1/4 of the users max HP, protecting the user from damage and effects until it breaks.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (165,'Struggle',101,50,1,18,'Used only if no move can be selected. User takes 1/4 of its max HP as recoil.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (166,'Sketch',101,0,1,0,'Copies the targets last used move into Sketchs moveslot permanently.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (167,'Triple Kick',90,10,10,1,'Hits three times in one turn. Second hit has 20 base power, third has 30.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (168,'Thief',100,60,25,16,'Takes the targets item if user has no item.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (169,'Spider Web',101,0,10,6,'Prevents the target from switching while the user is on the field.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (170,'Mind Reader',101,0,5,0,'User cannot miss the target next turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (171,'Nightmare',100,0,15,7,'Fails unless the target is asleep. Target 1/4 damage every turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (172,'Flame Wheel',100,60,25,9,'Has a 10% chance to burn the target. Defrosts user.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (173,'Snore',100,50,15,0,'Has a 30% chance to flinch. Fails unless user is asleep.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (174,'Curse',101,0,10,7,'If user is a Ghost, it losses 1/2 its HP and target takes 1/4 each turn. Otherwise, raises the users Atk and Def by one stage, but lowers Speed.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (175,'Flail',100,1,15,0,'Has more power when the user has less HP remaining, with a maximum of 200 power.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (176,'Conversion 2',101,0,30,0,'Changes the users type to a random type which resists or is immune to the last move used against it.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (177,'Aeroblast',95,100,5,2,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (178,'Cotton Spore',100,0,40,11,'Lowers the targets Speed by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (179,'Reversal',100,1,15,1,'Has more power when the user has less HP remaining, with a maximum of 200 power.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (180,'Spite',100,0,10,7,'Lowers the PP of the targets last used move by four.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (181,'Powder Snow',100,40,25,14,'Has a 10% chance to freeze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (182,'Protect',101,0,10,0,'Prevents attacks from hitting the user this turn. 50% chance to fail if used last turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (183,'Mach Punch',100,40,30,1,'A punch is thrown at wicked speed to strike first.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (184,'Scary Face',100,0,10,0,'Lowers the targets Speed by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (185,'Feint Attack',101,60,20,16,'Has perfect accuracy.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (186,'Sweet Kiss',75,0,10,17,'Confuses the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (187,'Belly Drum',101,0,10,0,'User loses 1/2 its max HP to raise its Attack stage to +6. Fails if user is below 1/2 HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (188,'Sludge Bomb',100,90,10,3,'Has a 30% chance to poison the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (189,'Mud-Slap',100,20,10,4,'Lowers the targets accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (190,'Octazooka',85,65,10,10,'Has a 50% chance to lower the targets accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (191,'Spikes',101,0,20,4,'Stackable entry hazard which hurts Pokémon affected by Ground. Deals 12.5% for one layer, 16.67% for two, 25% for three.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (192,'Zap Cannon',50,120,5,12,'Paralyzes the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (193,'Foresight',101,0,40,0,'Removes targets immunities to Normal and Fighting and sets its evasion stage to 0.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (194,'Destiny Bond',101,0,5,7,'If the user is KOed this turn, the Pokémon which KOed it faints.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (195,'Perish Song',101,0,5,0,'All Pokémon on the field faint after three turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (196,'Icy Wind',95,55,15,14,'Lowers the targets Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (197,'Detect',101,0,5,1,'Prevents attacks from hitting the user this turn. 50% chance to fail if used last turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (198,'Bone Rush',90,25,10,4,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (199,'Lock-On',101,0,5,0,'User cannot miss the target next turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (200,'Outrage',100,120,10,15,'User cannot select another attack or switch for 2-3 turns, then the user becomes confused.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (201,'Sandstorm',101,0,10,5,'Changes the weather to a sandstorm for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (202,'Giga Drain',100,75,10,11,'Heals the user by half the damage inflicted.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (203,'Endure',101,0,10,0,'Leaves the user with 1 HP if it would be KOed this turn. 50% chance to fail if used last turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (204,'Charm',100,0,20,17,'Lowers the targets Attack by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (205,'Rollout',90,30,20,5,'Locks user into this move. Power doubles with every successive hit, maxing out after 5 turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (206,'False Swipe',100,40,40,0,'Target is left at 1 HP if this attack would KO.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (207,'Swagger',90,0,15,0,'Confuses the target and raises its Attack by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (208,'Milk Drink',101,0,10,0,'Heals the user by half its max HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (209,'Spark',100,65,20,12,'Has a 30% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (210,'Fury Cutter',95,40,20,6,'Power doubles with every successive hit, maxing out after 5 turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (211,'Steel Wing',90,70,25,8,'Has a 10% chance to raise the users Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (212,'Mean Look',101,0,5,0,'Prevents the target from switching while the user is on the field.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (213,'Attract',100,0,15,0,'If target is opposite gender to user, infatuates target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (214,'Sleep Talk',101,0,10,0,'Randomly uses one of the users other moves. Fails unless user is asleep.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (215,'Heal Bell',101,0,5,0,'Removes all major status effects from users team.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (216,'Return',100,1,20,0,'Higher power if user has high happiness, up to a maximum of 102.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (217,'Present',90,1,15,0,'Either has 40, 80, or 120 base power or heals the target by 1/4.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (218,'Frustration',100,1,20,0,'Higher power if user has low happiness, up to a maximum of 102.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (219,'Safeguard',101,0,25,0,'Protects the users team from major status ailments and confusion for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (220,'Pain Split',101,0,20,0,'Adds the user and targets HP, then shares it equally.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (221,'Sacred Fire',95,100,5,9,'Has a 50% chance to burn the target. Defrosts user.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (222,'Magnitude',100,1,30,4,'Power varies randomly from 10 to 150. Can hit and has double power against Digging targets.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (223,'Dynamic Punch',50,100,5,1,'Confuses the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (224,'Megahorn',85,120,10,6,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (225,'Dragon Breath',100,60,20,15,'Has a 30% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (226,'Baton Pass',101,0,40,0,'Switches out the user giving stat changes and most volatile effects to the replacement.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (227,'Encore',100,0,5,0,'Makes the target repeat its last move for three turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (228,'Pursuit',100,40,20,16,'If the target switches, hits instantly with double power.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (229,'Rapid Spin',100,20,40,0,'Removes foes entry hazards, binding moves affecting the user, and Leech Seed.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (230,'Sweet Scent',100,0,20,0,'Lowers the targets evasion by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (231,'Iron Tail',75,100,15,8,'Has a 30% chance to lower the targets Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (232,'Metal Claw',95,50,35,8,'Has a 10% chance to raise the users Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (233,'Vital Throw',101,70,10,1,'Has perfect accuracy. Priority -1.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (234,'Morning Sun',101,0,5,0,'Heals user by half its max HP. 2/3 healing in sun, 1/4 in hail, rain, or sandstorm.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (235,'Synthesis',101,0,5,11,'Heals user by half its max HP. 2/3 healing in sun, 1/4 in hail, rain, or sandstorm.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (236,'Moonlight',101,0,5,17,'Heals user by half its max HP. 2/3 healing in sun, 1/4 in hail, rain, or sandstorm.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (237,'Hidden Power',100,60,15,0,'Power and type depend upon users IVs.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (238,'Cross Chop',80,100,5,1,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (239,'Twister',100,40,20,15,'Has a 20% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (240,'Rain Dance',101,0,5,10,'Changes the weather to rain for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (241,'Sunny Day',101,0,5,9,'Changes the weather to strong sunlight for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (242,'Crunch',100,80,15,16,'Has a 20% chance to lower the targets Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (243,'Mirror Coat',100,1,20,13,'Inflicts twice the damage the user received from the last special hit it took.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (244,'Psych Up',101,0,10,0,'User copies the foes stat stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (245,'Extreme Speed',100,80,5,0,'An extremely fast and powerful attack.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (246,'Ancient Power',100,60,5,5,'Has a 10% chance to raise all of the users stats bar evasion and accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (247,'Shadow Ball',100,80,15,7,'Has a 20% chance to lower the targets Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (248,'Future Sight',100,120,10,13,'Target takes damage two turns after the attack is used.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (249,'Rock Smash',100,40,15,1,'Has a 50% chance to lower the targets Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (250,'Whirlpool',85,35,15,10,'Target cannot switch and takes 1/16 damage per turn for 4-5 turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (251,'Beat Up',100,1,10,16,'Hits once for every non-fainted teammate. Uses a modified damage formula.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (252,'Fake Out',100,40,10,0,'Fails if user has used a move since entering the field. Flinches target. Priority level +3.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (253,'Uproar',100,90,10,0,'Attacks for 2-5 turns. All Pokémon wake and none can fall asleep during the attack.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (254,'Stockpile',101,0,20,0,'Raises the users Defense and Special Defense by one stage. Adds one to the Stockpile count for Spit Up and Swallow.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (255,'Spit Up',100,1,10,0,'Power is 100 times the amount of Stockpile count. Sets stockpile count to 0.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (256,'Swallow',101,0,10,0,'Recovers more HP with more Stockpiles. One gives 1/4, two gives 1/2 HP, three gives full HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (257,'Heat Wave',90,95,10,9,'Has a 10% chance to burn the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (258,'Hail',101,0,10,14,'Changes the weather to a hailstorm for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (259,'Torment',100,0,15,16,'Prevents the target from using the same move twice in a row.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (260,'Flatter',100,0,15,16,'Confuses the target and raises its Special Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (261,'Will-O-Wisp',85,0,15,9,'Burns the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (262,'Memento',100,0,10,16,'The user faints and lowers targets Special Attack and Attack two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (263,'Facade',100,70,20,0,'Doubles power if user is burned, paralyzed, or poisoned.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (264,'Focus Punch',100,150,20,1,'User flinches if it takes damage before attacking.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (265,'Smelling Salts',100,70,10,0,'If the target is paralyzed, inflicts double damage and cures the paralysis.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (266,'Follow Me',101,0,20,0,'Redirects the opponents single-target attacks to the user where possible this turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (267,'Nature Power',101,0,20,0,'Becomes a different move depending upon the terrain (Tri Attack in multiplayer battles).')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (268,'Charge',101,0,20,12,'Raises the users Special Defense by one stage. Users Electric moves have double power next turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (269,'Taunt',100,0,20,16,'Target cannot use non-offensive moves for three turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (270,'Helping Hand',101,0,20,0,'Target ally deals x1.5 damage this turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (271,'Trick',100,0,10,13,'User swaps items with the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (272,'Role Play',101,0,10,13,'Changes the users ability to the targets.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (273,'Wish',101,0,10,0,'Pokémon in users place recovers half users max HP at the end of the next turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (274,'Assist',101,0,20,0,'Randomly selects and uses a move known by another Pokémon on the users team.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (275,'Ingrain',101,0,20,11,'Prevents the user from leaving the field. User regains 1/16 of its max HP every turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (276,'Superpower',100,120,5,1,'Lowers the users Attack and Defense by one stage after inflicting damage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (277,'Magic Coat',101,0,15,13,'Reflects back the first effect move used on the user this turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (278,'Recycle',101,0,10,0,'User recovers the item it last used up.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (279,'Revenge',100,60,10,1,'Has double power if the user has taken damage this turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (280,'Brick Break',100,75,15,1,'Removes the effects of foes Reflect and Light Screen.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (281,'Yawn',101,0,10,0,'Puts the target to sleep at the end of the next turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (282,'Knock Off',100,65,25,16,'Removes targets held item.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (283,'Endeavor',100,1,5,0,'If user has less HP than target, sets targets HP to equal users.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (284,'Eruption',100,150,5,9,'Power decreases if user has less HP remaining.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (285,'Skill Swap',101,0,10,13,'User swaps abilities with the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (286,'Imprison',101,0,10,13,'Prevents opponents from using any moves that the user knows.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (287,'Refresh',101,0,20,0,'Removes major status conditions from user (poison, paralysis, and burn).')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (288,'Grudge',101,0,5,7,'If the user faints before it next moves, the move that fainted it will have its PP set to 0.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (289,'Snatch',101,0,10,16,'Steals the targets move, if its self-targeted.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (290,'Secret Power',100,70,20,0,'Has a 30% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (291,'Dive',100,80,10,10,'Dodges attacks on first turn, strikes on second.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (292,'Arm Thrust',100,15,20,1,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (293,'Camouflage',101,0,20,0,'Users type changes to match the terrain (Normal in multiplayer battles).')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (294,'Tail Glow',101,0,20,6,'Raises the users Special Attack by three stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (295,'Luster Purge',100,70,5,13,'Has a 50% chance to lower the targets Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (296,'Mist Ball',100,70,5,13,'Has a 50% chance to lower the targets Special Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (297,'Feather Dance',100,0,15,2,'Lowers the targets Attack by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (298,'Teeter Dance',100,0,20,0,'Confuses all targets.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (299,'Blaze Kick',90,85,10,9,'Has a high critical hit rate. Has a 10% chance to burn the target..')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (300,'Mud Sport',101,0,15,4,'Halves damage from all Electric attacks until user leaves the field.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (301,'Ice Ball',90,30,20,14,'Locks user into this move. Power doubles with every successive hit, maxing out after 5 turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (302,'Needle Arm',100,60,15,11,'Has a 30% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (303,'Slack Off',101,0,10,0,'Heals the user by half its max HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (304,'Hyper Voice',100,90,10,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (305,'Poison Fang',100,50,15,3,'Has a 30% chance to badly poison the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (306,'Crush Claw',95,75,10,0,'Has a 50% chance to lower the targets Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (307,'Blast Burn',90,150,5,9,'User cannot attack or switch the turn after using this attack.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (308,'Hydro Cannon',90,150,5,10,'User cannot attack or switch the turn after using this attack.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (309,'Meteor Mash',90,90,10,8,'Has a 20% chance to raise the users Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (310,'Astonish',100,30,15,7,'Has a 30% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (311,'Weather Ball',100,50,10,0,'Power doubles in a weather condition, and type changes to match the weather.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (312,'Aromatherapy',101,0,5,11,'Removes all major status effects from users team.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (313,'Fake Tears',100,0,20,16,'Lowers the targets Special Defense by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (314,'Air Cutter',95,60,25,2,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (315,'Overheat',90,130,5,9,'Lowers the users Special Attack by two stages after inflicting damage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (316,'Odor Sleuth',101,0,40,0,'Removes targets immunities to Normal and Fighting and sets its evasion stage to 0.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (317,'Rock Tomb',95,60,15,5,'Lowers the targets Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (318,'Silver Wind',100,60,5,6,'Has a 10% chance to raise all of the users stats bar evasion and accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (319,'Metal Sound',85,0,40,8,'Lowers the targets Special Defense by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (320,'Grass Whistle',55,0,15,11,'Puts the target to sleep.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (321,'Tickle',100,0,20,0,'Lowers the targets Attack and Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (322,'Cosmic Power',101,0,20,13,'Raises the users Defense and Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (323,'Water Spout',100,150,5,10,'Power decreases if user has less HP remaining.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (324,'Signal Beam',100,75,15,6,'Has a 10% chance to confuse the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (325,'Shadow Punch',101,60,20,7,'Has perfect accuracy.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (326,'Extrasensory',100,80,20,13,'Has a 10% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (327,'Sky Uppercut',90,85,15,1,'Can hit Bounceing, Flying, and Sky Dropped targets.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (328,'Sand Tomb',85,35,15,4,'Target cannot switch and takes 1/16 damage per turn for 4-5 turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (329,'Sheer Cold',30,1,5,14,'Knocks out the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (330,'Muddy Water',85,90,10,10,'Has a 30% chance to lower the targets accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (331,'Bullet Seed',100,25,30,11,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (332,'Aerial Ace',101,60,20,2,'Has perfect accuracy.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (333,'Icicle Spear',100,25,30,14,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (334,'Iron Defense',101,0,15,8,'Raises the users Defense by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (335,'Block',101,0,5,0,'Prevents the target from switching while the user is on the field.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (336,'Howl',101,0,40,0,'Raises the users Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (337,'Dragon Claw',100,80,15,15,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (338,'Frenzy Plant',90,150,5,11,'User cannot attack or switch the turn after using this attack.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (339,'Bulk Up',101,0,20,1,'Raises the users Attack and Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (340,'Bounce',85,85,5,2,'Dodges attacks on first turn, strikes on second. Has a 30% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (341,'Mud Shot',95,55,15,4,'Lowers the targets Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (342,'Poison Tail',100,50,25,3,'Has a high critical hit rate. Has a 10% chance to poison the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (343,'Covet',100,60,25,0,'Takes the targets item if user has no item.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (344,'Volt Tackle',100,120,15,12,'User receives 1/3 the damage inflicted as recoil. Has a 10% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (345,'Magical Leaf',101,60,20,11,'Has perfect accuracy.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (346,'Water Sport',101,0,15,10,'Halves damage from all Electric attacks until user leaves the field.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (347,'Calm Mind',101,0,20,13,'Raises the users Special Attack and Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (348,'Leaf Blade',100,90,15,11,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (349,'Dragon Dance',101,0,20,15,'Raises the users Attack and Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (350,'Rock Blast',90,25,10,5,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (351,'Shock Wave',101,60,20,12,'Has perfect accuracy.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (352,'Water Pulse',100,60,20,10,'Has a 20% chance to confuse the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (353,'Doom Desire',100,140,5,8,'Target takes damage two turns after the attack is used.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (354,'Psycho Boost',90,140,5,13,'Lowers the users Special Attack by two stages after inflicting damage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (355,'Roost',101,0,10,2,'Heals the user by half its max HP and loses its flying type until the end of the turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (356,'Gravity',101,0,5,13,'Disables moves and immunities that involve flying or levitating for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (357,'Miracle Eye',101,0,40,13,'Removes targets immunity to Psychic and sets its evasion stage to 0.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (358,'Wake-Up Slap',100,70,10,1,'Power doubles if foe is asleep, cures sleep status')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (359,'Hammer Arm',90,100,10,1,'Lowers users Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (360,'Gyro Ball',100,1,5,8,'Power raises when the user has lower Speed than the target, up to a maximum of 150.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (361,'Healing Wish',101,0,10,13,'The user faints and fully heals the Pokémon replacing it.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (362,'Brine',100,65,10,10,'Has double power if target has less than half HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (363,'Natural Gift',100,1,15,0,'Power and type depend on the held berry.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (364,'Feint',100,30,10,0,'Not blocked by Protect or Detect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (365,'Pluck',100,60,20,2,'If target has a berry, inflicts double damage and activates berry for user.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (366,'Tailwind',101,0,15,2,'Doubles the Speed of all Pokémon on the users team for three turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (367,'Acupressure',101,0,30,0,'Raises one stat chosen at random by two stages for the user or teammate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (368,'Metal Burst',100,1,10,8,'Inflicts 1.5x the damage the user received from the last hit it took.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (369,'U-turn',100,70,20,6,'User must switch out after attacking.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (370,'Close Combat',100,120,5,1,'Lowers the users Defense and Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (371,'Payback',100,50,10,16,'Power is doubled if the target has already moved this turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (372,'Assurance',100,60,10,16,'Power is doubled if the target has already received damage this turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (373,'Embargo',100,0,15,16,'Targets held items will not activate for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (374,'Fling',100,1,10,16,'Throws users held item at the target. Power and effect depends on the item.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (375,'Psycho Shift',100,0,10,13,'If user has a major status condition and target does not, transfers status to the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (376,'Trump Card',101,1,5,0,'Power increases when this move has less PP, up to a maximum of 200.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (377,'Heal Block',100,0,15,13,'Prevents target from restoring its HP for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (378,'Wring Out',100,1,5,0,'Higher power against targets with more HP remaining. 110 max base power.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (379,'Power Trick',101,0,10,13,'User swaps its Attack and Defense stats.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (380,'Gastro Acid',100,0,10,3,'Nullifies targets ability until it leaves battle.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (381,'Lucky Chant',101,0,30,0,'Users team cannot be critically hit for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (382,'Me First',101,1,20,0,'Uses the targets selected move against it with 1.5x power. Fails if target moves first.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (383,'Copycat',101,0,20,0,'Uses the last move used by any Pokémon.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (384,'Power Swap',101,0,10,13,'User swaps Attack and Special Attack stages with the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (385,'Guard Swap',101,0,10,13,'User swaps Defense and Special Defense stages with the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (386,'Punishment',100,1,5,16,'Power increases against targets with more raised stats, up to a maximum of 200.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (387,'Last Resort',100,140,5,0,'Can only be selected after user has used all its other moves.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (388,'Worry Seed',100,0,10,11,'Changes the targets ability to Insomnia.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (389,'Sucker Punch',100,80,5,16,'Fails unless the target selects a damaging move. Priority +1')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (390,'Toxic Spikes',101,0,20,3,'Stackable entry hazard which poisons Pokémon affected by Ground. Normal poison for one layer, bad poison for two.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (391,'Heart Swap',101,0,10,13,'User swaps stat stages with the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (392,'Aqua Ring',101,0,20,10,'Restores 1/16 of the users max HP each turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (393,'Magnet Rise',101,0,10,12,'User becomes immune to Ground moves for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (394,'Flare Blitz',100,120,15,9,'User receives 1/3 the damage inflicted as recoil. Has a 10% chance to burn the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (395,'Force Palm',100,60,10,1,'Has a 30% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (396,'Aura Sphere',101,80,20,1,'Has perfect accuracy.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (397,'Rock Polish',101,0,20,5,'Raises the users Speed by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (398,'Poison Jab',100,80,20,3,'Has a 30% chance to poison the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (399,'Dark Pulse',100,80,15,16,'Has a 20% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (400,'Night Slash',100,70,15,16,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (401,'Aqua Tail',90,90,10,10,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (402,'Seed Bomb',100,80,15,11,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (403,'Air Slash',95,75,15,2,'Has a 30% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (404,'X-Scissor',100,80,15,6,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (405,'Bug Buzz',100,90,10,6,'Has a 10% chance to lower the targets Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (406,'Dragon Pulse',100,85,10,15,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (407,'Dragon Rush',75,100,10,15,'Has a 20% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (408,'Power Gem',100,80,20,5,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (409,'Drain Punch',100,75,10,1,'Heals the user by half the damage inflicted.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (410,'Vacuum Wave',100,40,30,1,'Always strikes first')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (411,'Focus Blast',70,120,5,1,'Has a 10% chance to lower the targets Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (412,'Energy Ball',100,90,10,11,'Has a 10% chance to lower the targets Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (413,'Brave Bird',100,120,15,2,'User receives 1/3 the damage inflicted as recoil.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (414,'Earth Power',100,90,10,4,'Has a 10% chance to lower the targets Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (415,'Switcheroo',100,0,10,16,'User swaps items with the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (416,'Giga Impact',90,150,5,0,'User cannot attack or switch the turn after using this attack.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (417,'Nasty Plot',101,0,20,16,'Raises the users Special Attack by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (418,'Bullet Punch',100,40,30,8,'Always strikes first')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (419,'Avalanche',100,60,10,14,'Has double power if the user has taken damage this turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (420,'Ice Shard',100,40,30,14,'Always strikes first')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (421,'Shadow Claw',100,70,15,7,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (422,'Thunder Fang',95,65,15,12,'Has a 10% chance to paralyze the target and a 10% chance to make the target flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (423,'Ice Fang',95,65,15,14,'Has a 10% chance to freeze the target and a 10% chance to make the target flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (424,'Fire Fang',95,65,15,9,'Has a 10% chance to burn the target and a 10% chance to make the target flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (425,'Shadow Sneak',100,40,30,7,'Always strikes first')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (426,'Mud Bomb',85,65,10,4,'Has a 30% chance to lower the targets accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (427,'Psycho Cut',100,70,20,13,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (428,'Zen Headbutt',90,80,15,13,'Has a 20% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (429,'Mirror Shot',85,65,10,8,'Has a 30% chance to lower the targets accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (430,'Flash Cannon',100,80,10,8,'Has a 10% chance to lower the targets Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (431,'Rock Climb',85,90,20,0,'Has a 20% chance to confuse the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (432,'Defog',101,0,15,2,'Lowers the targets evasion by one stage. Removes field effects from the foes side.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (433,'Trick Room',101,0,5,13,'For five turns, slower Pokémon will act before faster Pokémon.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (434,'Draco Meteor',90,130,5,15,'Lowers the users Special Attack by two stages after inflicting damage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (435,'Discharge',100,80,15,12,'Has a 30% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (436,'Lava Plume',100,80,15,9,'Has a 30% chance to burn the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (437,'Leaf Storm',90,130,5,11,'Lowers the users Special Attack by two stages after inflicting damage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (438,'Power Whip',85,120,10,11,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (439,'Rock Wrecker',90,150,5,5,'User cannot attack or switch the turn after using this attack.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (440,'Cross Poison',100,70,20,3,'Has a high critical hit rate. Has a 10% chance to poison the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (441,'Gunk Shot',80,120,5,3,'Has a 30% chance to poison the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (442,'Iron Head',100,80,15,8,'Has a 30% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (443,'Magnet Bomb',101,60,20,8,'Has perfect accuracy.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (444,'Stone Edge',80,100,5,5,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (445,'Captivate',100,0,20,0,'If target is opposite gender to user, lowers the targets Special Attack by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (446,'Stealth Rock',101,0,20,5,'Entry hazard which hurts Pokémon depending on the effectiveness of Rock moves. Deals 12.5% when neutral.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (447,'Grass Knot',100,1,20,11,'More power against to heavier targets, with a maximum of 120.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (448,'Chatter',100,65,20,2,'Confuses foe')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (449,'Judgment',100,100,10,0,'Attack type changes to match held Plate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (450,'Bug Bite',100,60,20,6,'If target has a berry, inflicts double damage and activates berry for user.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (451,'Charge Beam',90,50,10,12,'Has a 70% chance to raise the users Special Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (452,'Wood Hammer',100,120,15,11,'User receives 1/3 the damage inflicted as recoil.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (453,'Aqua Jet',100,40,20,10,'Always strikes first')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (454,'Attack Order',100,90,15,6,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (455,'Defend Order',101,0,10,6,'Raises the users Defense and Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (456,'Heal Order',101,0,10,6,'Heals the user by half its max HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (457,'Head Smash',80,150,5,5,'User receives 1/2 the damage inflicted as recoil.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (458,'Double Hit',90,35,10,0,'Hits twice in one turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (459,'Roar of Time',90,150,5,15,'User cannot attack or switch the turn after using this attack.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (460,'Spacial Rend',95,100,5,15,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (461,'Lunar Dance',101,0,10,13,'The user faints and fully heals the Pokémon replacing it.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (462,'Crush Grip',100,1,5,0,'Higher power against targets with more HP remaining. 110 max base power.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (463,'Magma Storm',75,100,5,9,'Traps foe')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (464,'Dark Void',80,0,10,16,'Puts all targets to sleep.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (465,'Seed Flare',85,120,5,11,'Has a 40% chance to lower the targets Special Defense by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (466,'Ominous Wind',100,60,5,7,'Has a 10% chance to raise all of the users stats bar evasion and accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (467,'Shadow Force',100,120,5,7,'Dodges attacks on first turn, strikes on second. Not blocked by Protect or Detect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (468,'Hone Claws',101,0,15,16,'Raises the users Attack and accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (469,'Wide Guard',101,0,10,5,'Prevents multi-target moves from hitting users team this turn. 50% chance to fail if used last turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (470,'Guard Split',101,0,10,13,'Averages users and targets Defense and Special Defense stats separately.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (471,'Power Split',101,0,10,13,'Averages users and targets Attack and Special Attack stats separately.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (472,'Wonder Room',101,0,10,13,'All Pokémons Defense and Special Defense stats are swapped for 5 turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (473,'Psyshock',100,80,10,13,'Damage is calculated using targets Defense stat.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (474,'Venoshock',100,65,10,3,'Has double power if the target is poisoned.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (475,'Autotomize',101,0,15,8,'Raises the users Speed by two stages and halves the users weight.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (476,'Rage Powder',101,0,20,6,'Redirects the opponents single-target attacks to the user where possible this turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (477,'Telekinesis',101,0,15,13,'Target is immune to Ground and all attacks against it have perfect acc for 3 turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (478,'Magic Room',101,0,10,13,'Held items will not activate and have no effect for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (479,'Smack Down',100,50,15,5,'Removes targets immunity to Ground.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (480,'Storm Throw',100,60,10,1,'Always hits critically unless the foe is protected from critical hits.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (481,'Flame Burst',100,70,15,9,'Does 1/16 damage to adjacent teammates.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (482,'Sludge Wave',100,95,10,3,'Has a 10% chance to poison the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (483,'Quiver Dance',101,0,20,6,'Raises the users Special Attack, Special Defense, and Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (484,'Heavy Slam',100,1,10,8,'Power is higher when the user weighs more than the target, up to a maximum of 120.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (485,'Synchronoise',100,120,15,13,'Hits all Pokémon that share a type with the user.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (486,'Electro Ball',100,1,10,12,'Power is higher when the user has greater Speed than the target, up to a maximum of 150.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (487,'Soak',100,0,20,10,'Changes the targets type to pure Water.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (488,'Flame Charge',100,50,20,9,'Raises the users Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (489,'Coil',101,0,20,3,'Raises the users Attack, Defense, and accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (490,'Low Sweep',100,65,20,1,'Lowers the targets Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (491,'Acid Spray',100,40,20,3,'Lowers the targets Special Defense by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (492,'Foul Play',100,95,15,16,'Damage is calculated using the targets attacking stat.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (493,'Simple Beam',100,0,15,0,'Changes the targets ability to Simple.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (494,'Entrainment',100,0,15,0,'Changes the targets ability to the users.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (495,'After You',101,0,15,0,'Makes the target act next this turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (496,'Round',100,60,15,0,'Has double power if a teammate used Round this turn. All allies using Round attack at once.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (497,'Echoed Voice',100,40,15,0,'Power increases by 100% for each consecutive use by user and teammates, to a maximum of 200.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (498,'Chip Away',100,70,20,0,'Ignores the targets Defense and evasion modifiers.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (499,'Clear Smog',101,50,15,3,'Resets the targets stat stages to zero.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (500,'Stored Power',100,20,10,13,'Has 20 extra base power for each stat boost the user has, to a maximum of 620.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (501,'Quick Guard',101,0,15,1,'Prevents priority moves from hitting users team this turn. 50% chance to fail if used last turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (502,'Ally Switch',101,0,15,13,'User switches places with teammate. Fails if in the center.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (503,'Scald',100,80,15,10,'Has a 30% chance to burn the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (504,'Shell Smash',101,0,15,0,'Raises users Attack, Special Attack, and Speed by two stages but lowers Defense and Special Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (505,'Heal Pulse',101,0,10,13,'Heals the target by half its max HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (506,'Hex',100,65,10,7,'Has double power if the target has a major status ailment.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (507,'Sky Drop',100,60,10,2,'Two turn attack, almost all moves miss both target and user on turn 1, deals damage on turn 2.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (508,'Shift Gear',101,0,10,8,'Raises the users Attack by one stage and its Speed by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (509,'Circle Throw',90,60,10,1,'Forces the target to switch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (510,'Incinerate',100,60,15,9,'Removes the targets Berry.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (511,'Quash',100,0,15,16,'Makes the target act last this turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (512,'Acrobatics',100,55,15,2,'Has double power if the user has no held item.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (513,'Reflect Type',101,0,15,0,'User becomes the targets type(s).')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (514,'Retaliate',100,70,5,0,'Has double power if a teammate fainted last turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (515,'Final Gambit',100,1,5,1,'The user faints and deals damage to target equal to remaining HP.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (516,'Bestow',101,0,15,0,'Gives users item to target. Fails if target has an item.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (517,'Inferno',50,100,5,9,'Burns the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (518,'Water Pledge',100,80,10,10,'If an ally used Grass Pledge this turn, halves foe teams Speed for four turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (519,'Fire Pledge',100,80,10,9,'If an ally used Water Pledge this turn, doubles the effect chance of users teams moves for four turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (520,'Grass Pledge',100,80,10,11,'If an ally used Fire Pledge this turn, foe team takes 1/8 damage every turn for four turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (521,'Volt Switch',100,70,20,12,'User must switch out after attacking.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (522,'Struggle Bug',100,50,20,6,'Lowers the targets Special Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (523,'Bulldoze',100,60,20,4,'Lowers the targets Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (524,'Frost Breath',90,60,10,14,'Always hits critically unless the foe is protected from critical hits.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (525,'Dragon Tail',90,60,10,15,'Forces the target to switch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (526,'Work Up',101,0,30,0,'Raises the users Attack and Special Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (527,'Electroweb',95,55,15,12,'Lowers the targets Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (528,'Wild Charge',100,90,15,12,'User receives 1/4 the damage inflicted as recoil.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (529,'Drill Run',95,80,10,4,'Has a high critical hit rate.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (530,'Dual Chop',90,40,15,15,'Hits twice in one turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (531,'Heart Stamp',100,60,25,13,'Has a 30% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (532,'Horn Leech',100,75,10,11,'Heals the user by half the damage inflicted.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (533,'Sacred Sword',100,90,15,1,'Ignores the targets Defense and evasion modifiers.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (534,'Razor Shell',95,75,10,10,'Has a 50% chance to lower the targets Defense by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (535,'Heat Crash',100,1,10,9,'Power is higher when the user weighs more than the target, up to a maximum of 120.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (536,'Leaf Tornado',90,65,10,11,'Has a 50% chance to lower the targets accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (537,'Steamroller',100,65,20,6,'Has a 30% chance to flinch. Double damage if target has used Minimize.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (538,'Cotton Guard',101,0,10,11,'Raises the users Defense by three stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (539,'Night Daze',95,85,10,16,'Has a 40% chance to lower the targets accuracy by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (540,'Psystrike',100,100,10,13,'Damage is calculated using targets Defense stat.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (541,'Tail Slap',85,25,10,0,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (542,'Hurricane',70,110,10,2,'Has a 30% chance to confuse the target. Has perfect acc in Rain, 50% in Sun.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (543,'Head Charge',100,120,15,0,'User receives 1/4 the damage inflicted as recoil.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (544,'Gear Grind',85,50,15,8,'Hits twice in one turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (545,'Searing Shot',100,100,5,9,'Has a 30% chance to burn the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (546,'Techno Blast',100,120,5,0,'Attack type changes to match held Drive.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (547,'Relic Song',100,75,10,0,'Has a 10% chance to sleep the target. Changes Meloettas form.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (548,'Secret Sword',100,85,10,1,'Damage is calculated using targets Defense stat.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (549,'Glaciate',95,65,10,14,'Lowers the targets Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (550,'Bolt Strike',85,130,5,12,'Has a 20% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (551,'Blue Flare',85,130,5,9,'Has a 20% chance to burn the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (552,'Fiery Dance',100,80,10,9,'Has a 50% chance to raise the users Special Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (553,'Freeze Shock',90,140,5,14,'Requires a charging turn. Has a 30% chance to paralyze the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (554,'Ice Burn',90,140,5,14,'Requires a charging turn. Has a 30% chance to burn the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (555,'Snarl',95,55,15,16,'Lowers the targets Special Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (556,'Icicle Crash',90,85,10,14,'Has a 30% chance to flinch.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (557,'V-create',95,180,5,9,'Lowers the users Defense, Special Defense, and Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (558,'Fusion Flare',100,100,5,9,'Doubles in power if used on the same turn after Fusion Bolt.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (559,'Fusion Bolt',100,100,5,12,'Doubles in power if used on the same turn after Fusion Flare.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (560,'Baby-Doll Eyes',100,0,30,17,'Lowers the targets accuracy by one stage. Priority level 1.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (561,'Boomburst',100,140,10,0,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (562,'Crafty Shield',101,0,10,17,'The user protects itself and its allies from status moves.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (563,'Dazzling Gleam',100,80,10,17,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (564,'Draining Kiss',100,50,20,17,'Heals the user by half the damage inflicted.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (565,'Fairy Wind',100,40,30,17,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (566,'Flying Press',95,80,10,1,'This move is Fighting and Flying type simultaneously.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (567,'Forests Curse',100,0,20,11,'Changes the targets type to pure Grass.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (568,'Freeze-Dry',100,70,20,14,'Has a 10% chance to freeze the target. Super-effective on water-types.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (569,'Geomancy',101,0,10,17,'Requires a charging turn. Raises the users Special Attack, Special Defence and Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (570,'Petal Blizzard',100,90,15,11,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (571,'Infestation',100,20,20,6,'Attacks for 4-5 rounds. Target cant switch during the attack.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (572,'Moonblast',100,95,15,17,'Has a 30% chance to lower the targets Special Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (573,'Mystical Fire',100,65,10,9,'Inflicts damage and lowers the targets Special Attack')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (574,'Noble Roar',100,0,30,0,'Lowers the targets Attack and Special Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (575,'Nuzzle',100,20,20,12,'Inflicts damage and paralyses the target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (576,'Oblivion Wing',100,80,10,2,'Heals the user by half the damage inflicted.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (577,'Parabolic Charge',100,50,20,12,'Heals the user by half the damage inflicted.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (578,'Phantom Force',100,90,10,7,'Dodges attacks on first turn, strikes on second. Not blocked by Protect or Detect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (579,'Play Rough',90,90,10,17,'Has a 10% chance to lower the targets Attack.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (580,'Play Nice',101,0,20,0,'Lowers the targets Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (581,'Trick-or-Treat',100,0,20,7,'Changes the targets type to pure Ghost.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (582,'Water Shuriken',100,15,20,10,'Hits 2-5 times. 3/8 chance for 2 and 3 hits, 1/8 for 4 and 5. Priority level 1.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (583,'Aromatic Mist',100,0,20,17,'Raises the Special Defense of users teammates.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (584,'Belch',90,120,10,3,'The user must eat a Berry to use this move.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (585,'Confide',101,0,20,0,'Lowers the targets Special Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (586,'Disarming Voice',101,40,15,17,'Has perfect accuracy.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (587,'Eerie Impulse',100,0,15,12,'Lowers the targets Special Attack by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (588,'Electric Terrain',101,0,10,12,'Pokémon on the ground no longer fall asleep for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (589,'Electrify',101,0,20,12,'The next move the target uses becomes Electric type.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (590,'Fairy Lock',101,0,10,17,'Target cant switch during the next turn.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (591,'Fell Stinger',100,30,25,6,'When the user knocks out the target with this move, the users Attack raises by two stages.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (592,'Flower Shield',101,0,10,17,'Raises Defense of all Grass Pokémon in battle.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (593,'Grassy Terrain',101,0,10,11,'Restores 1/16 of the users max HP for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (594,'Ion Deluge',101,0,25,12,'Changes Normal-type moves of the user to Electric-type moves.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (595,'Kings Shield',101,0,10,8,'Prevents attacks from hitting the user this turn. Lowers the Attack of any Pokémon which makes direct contact.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (596,'Lands Wrath',100,90,10,4,'Inflicts regular damage with no additional effect.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (597,'Magnetic Flux',101,0,20,12,'Raises the Defense and Special Defense of the users teammates with the Plus or Minus ability.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (598,'Mat Block',101,0,15,1,'Prevents attacks from hitting the user this turn. Does not stop status moves.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (599,'Misty Terrain',101,0,10,17,'Protects Pokémon on the ground from status changes for five turns.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (600,'Parting Shot',100,0,20,16,'Lowers the targets Attack and Special Attack by one stage and then user switches with another Pokémon.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (601,'Powder',100,0,20,6,'Damages the target if it uses a Fire-type move.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (602,'Power-Up Punch',100,40,10,1,'Inflicts damage and raises the users Attack by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (603,'Rototiller',101,0,10,4,'Raises the Attack and Special Attack of Grass Pokémon.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (604,'Spiky Shield',101,0,10,11,'Prevents attacks from hitting the user this turn. Damages any attacker who makes direct contact.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (605,'Sticky Web',101,0,20,6,'Entry hazard which lower the Speed by one stage.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (606,'Topsy-Turvy',100,0,20,16,'Reverses all stat changes on the target Pokémon')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (607,'Venom Drench',100,0,20,3,'Inflicts damage. Lowers Attack, Special Attack and Speed of a poisoned target.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (608,'Happy Hour',101,0,30,0,'Doubles prize money received after battle.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (609,'Celebrate',101,0,40,0,'Congratulates you on your special day.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (610,'Hold Back',100,40,40,0,'Target is left at 1 HP if this attack would KO.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (611,'Diamond Storm',95,100,5,5,'Has a 50% chance to raise the users Defense.')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (612,'Light of Ruin',90,140,5,17,'Unreleased')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (613,'Steam Eruption',95,110,5,10,'Unreleased')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (614,'Hyperspace Hole',101,80,5,13,'Unreleased')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (615,'Hold Hands',101,0,40,0,'Unreleased')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (616,'Thousand Arrows',100,90,10,4,'Unreleased')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (617,'Thousand Waves',100,90,10,4,'Unreleased')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (618,'Origin Pulse',85,110,10,10,'Unreleased')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (619,'Precipice Blades',85,120,10,4,'Unreleased')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (620,'Dragon Ascent',100,120,5,2,'Unreleased')
INSERT INTO moves (mid,mname,accuracy,power,pp,type,movedesc) VALUES (621,'Hyperspace Fury',101,100,5,16,'Unreleased')
BUILD SUCCESSFUL (total time: 0 seconds)
